spring:
  h2:
    console:
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  address: 0.0.0.0

cors:
  allowed-origins:
    - http://localhost:8080
    - http://localhost:3000
    - http://localhost:3001
