spring:
  application:
    name: kotconnect
  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
    open-in-view: true

  datasource:
    url: jdbc:h2:mem:kotconnect
    driver-class-name: org.h2.Driver
    username: kotconnect
    password: kotconnect123

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          authority-prefix: ""

jwt:
  secret-key: d2ViNC1ub3Qtc28tc2VjcmV0LWFjY2Vzcy1zZWNyZXQ=

cors:
  allowed-origins:
    - http://localhost
    - http://localhost:8080
    - http://localhost:8081
    - http://localhost:3000
    - http://localhost:3001
